lyrics:
  rateLimit:
    maxPerHour: 10
    cooldown: 5000
  batch_draw_max_count: 5
quickMath:
  answer_timeout_ms: 30000
  normal_mode_max_attempts: 3
russianRoulette:
  initial_spins: 4
  default_bullet_count: 1
  auto_start_delay_ms: 30000
  cylinder_capacity: 8
  initial_foresights: 1
  initial_skips: 1
